### ISSUE TITLE
Homepage hero image should be customizable

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-barcelona#12]
The largest image, at the top of the homepage is not customizable. We should make that customizable like the other banner images in this theme.

<img width="1267" alt="home" src="https://user-images.githubusercontent.com/1108337/27196481-72d22bae-51bf-11e7-9d66-8eff8e700009.png">

**Comment by rudy-sasquatchstudio** [comment]
Done.  Available in next PR
