### ISSUE TITLE
Make the home + shop items in menu hard coded

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-barcelona#13]
Currently, the shop menu, which has a drop-down list of categories is hard coded.

Let's make Home + Shop items in the menu hard coded, so that the drop-down category navigation can be dynamic. This is similar to how the Zest theme handles it.

<img width="651" alt="home" src="https://user-images.githubusercontent.com/1108337/27196578-d4198ee8-51bf-11e7-9c2b-88227f5a4006.png">

**Comment by rudy-sasquatchstudio** [comment]
Done. Available in PR
